from enum import Enum


class AttackCategory(str, Enum):
    DIRECT_PROMPT_INJECTION = "DIRECT_PROMPT_INJECTION"
    INDIRECT_PROMPT_INJECTION = "INDIRECT_PROMPT_INJECTION"
    SYSTEM_PROMPT_EXTRACTION = "SYSTEM_PROMPT_EXTRACTION"
    ROLE_HIJACKING = "ROLE_HIJACKING"
    SAFETY_BYPASS = "SAFETY_BYPASS"
    OBFUSCATED_JAILBREAK = "OBFUSCATED_JAILBREAK"
    MULTI_TURN_JAILBREAK = "MULTI_TURN_JAILBREAK"
    CONTEXT_POISONING = "CONTEXT_POISONING"
    TOOL_ABUSE = "TOOL_ABUSE"
    PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    UNKNOWN_ADVERSARIAL = "UNKNOWN_ADVERSARIAL"


class SecuritySource(str, Enum):
    USER_INPUT = "USER_INPUT"
    CONVERSATION_HISTORY = "CONVERSATION_HISTORY"
    RETRIEVED_CONTEXT = "RETRIEVED_CONTEXT"
    MODEL_OUTPUT = "MODEL_OUTPUT"
    TOOL_REQUEST = "TOOL_REQUEST"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
